project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
]

project/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
]

project/users/urls.py
from django.urls import path
from django.urls import path
from .views import login_view, signup_view, logout_view

app_name = "users"

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

project/quotes/models.py
from django.db import models

project/quotes/views.py
from django.shortcuts import render
from .utils import get_mongodb

def main(request):
    db = get_mongodb()
    quotes = db.quotes.find()
    return render(request, "quotes/index.html", context={"quotes": quotes})

project/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form})

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'users/signup.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('/')

project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link href="{% static 'quotes/style.css' %}" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                {% if user.is_authenticated %}
                <p>Welcome, {{ user.username }}!</p>
                    <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                {% else %}
                    <a href="{% url 'users:signup' %}" class="btn btn-primary">Sign up</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                {% endif %}
            </div>
        </div>
        {% block content %} {% endblock %}
    </div>
</body>
</html>

project/quotes/templates/quotes/index.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="row">
    <div class="col-md-8">

    {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.text}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author}}</small></span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags %}
                <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
            
        </div>
    </div>
</div>

{% endblock %}

project/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Page</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    {% load static %}
    <link href="{% static 'users/style.css' %}" rel="stylesheet">
</head>
<body>
<div class="box-form">
    <div class="left">
        <div class="overlay">
            <h1>Welcome.</h1>
            <p>Welcome to my site</p>
        </div>
    </div>

    <div class="right">
        <h5>Login</h5>
        <form method="post" action="{% url 'users:login' %}">
			{% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Login</button>
        </form>
    </div>
</div>
</body>
</html>

project/users/templates/users/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up Page</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
{% load static %}
    <link href="{% static 'users/style.css' %}" rel="stylesheet">
</head>
<body>
<div class="box-form">
    <div class="left">
        <div class="overlay">
            <h1>Welcome.</h1>
            <p>Welcome to my site</p>
        </div>
    </div>

    <div class="right">
            <h5>Register</h5>
            <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            <br><br>
            <div class="remember-me--forget-password"></div>
            <br>
            {{ form.as_p }}
            <button type="submit">Register</button>
        </form>
    </div>
</div>
</body>
</html>